_BASE_: "../Base-RCNN-C4.yaml"
MODEL:
  META_ARCHITECTURE: "GeneralizedR"
  PIXEL_MEAN: [123.675, 116.280, 103.530, 92.806, 92.806, 92.806]
  PIXEL_STD: [58.395, 57.120, 57.375, 34.796, 34.796, 34.796]
  BACKBONE:
    NAME: "build_resnet_backbone"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  RESNETS:
    OUT_FEATURES: ["res2","res3","res4","res5",]
  FPN:
    IN_FEATURES: ["res5",]

  ANCHOR_GENERATOR:
    SIZES: [[32], [64], [128], [256], [512]]  # One size for each in feature map
    ASPECT_RATIOS: [[0.5, 1.0, 2.0]]  # Three aspect ratios (same for all in feature maps)
  RPN:
    IN_FEATURES: ["p2", "p3", "p4", "p5", "p6"]
    PRE_NMS_TOPK_TRAIN: 2000  # Per FPN level
    PRE_NMS_TOPK_TEST: 1000  # Per FPN level
    # Detectron1 uses 2000 proposals per-batch,
    # (See "modeling/rpn/rpn_outputs.py" for details of this legacy issue)
    # which is approximately 1000 proposals per-image since the default batch size for FPN is 2.
    POST_NMS_TOPK_TRAIN: 1000
    POST_NMS_TOPK_TEST: 1000
  ROI_HEADS:
    NAME: "StandardROIHeads"
    NUM_CLASSES: 10
    IN_FEATURES: ["p2", "p3", "p4", "p5"]
  ROI_BOX_HEAD:
    NAME: "FastRCNNConvFCHead"
    NUM_FC: 1
    POOLER_RESOLUTION: 7
  
SEED: 40244023
TEST:
  EVAL_PERIOD: 19000
SOLVER:
  IMS_PER_BATCH: 24
  BASE_LR: 0.02
  STEPS: (6000, 8000)
  MAX_ITER: 9000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
VERSION: 2
DATASETS:
  TRAIN: ('rgbt_trainval',)
  TEST: ('rgbt_trainval',)
  
OUTPUT_DIR: ./res